### ISSUE TITLE
Outstanding commits

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/turtle-race#4]
@caitlynraspberrypi @ninaszymor 

you both have commits in draft - can they be pushed to master?

**Comment by ninaszymor** [comment]
@martinohanlon yes from me.

**Comment by caitlynraspberrypi** [comment]
Yep!

**Comment by MarcScott** [comment]
I'm assuming this was handled as part of the meta update

**Comment by martinohanlon** [comment]
yes
